# Generated by Django 4.2 on 2023-04-11 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lanbuddy_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='game',
        ),
        migrations.AddField(
            model_name='game',
            name='users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lanbuddy_api.user'),
        ),
    ]
