# Generated by Django 4.2 on 2023-04-11 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lanbuddy_api', '0002_remove_user_game_game_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='users',
        ),
        migrations.AddField(
            model_name='user',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='lanbuddy_api.game'),
        ),
    ]
