# Generated by Django 4.2 on 2023-04-12 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lanbuddy_api', '0003_remove_game_users_user_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='user_name',
        ),
    ]
