# Generated by Django 4.2 on 2023-04-12 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lanbuddy_api', '0003_remove_game_users_user_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='lanbuddy_api.game'),
        ),
    ]
