# Generated by Django 4.2 on 2023-04-13 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lanbuddy_api', '0004_alter_user_game'),
        ('lanbuddy_api', '0005_alter_user_game'),
    ]

    operations = [
    ]
